# ---
# sensors:

# TODO: fix names

- platform: statistics
  # TODO change from Power to Energy
  name: ASHP Last Minute Power Consumed Clamp
  entity_id: sensor.ashp_clamp_power
  state_characteristic: average_linear
  unique_id: statistics_sensor_clamp_energy_consumed_last_minute
  max_age:
    minutes: 1
  keep_last_sample: true

- platform: statistics
  name: ASHP Last Hour Energy Consumed Clamp
  entity_id: sensor.ashp_clamp_energy
  unique_id: statistics_sensor_clamp_last_hour_energy_consumed
  state_characteristic: change
  max_age:
    hours: 1
  keep_last_sample: false

- platform: statistics
  name: ASHP Last Hour Energy Consumed ESP
  entity_id: sensor.m5atom_dev_total_consumed_energy
  unique_id: statistics_sensor_atom_last_hour_energy_consumed
  state_characteristic: change
  max_age:
    hours: 1
  keep_last_sample: false

- platform: statistics
  name: ASHP Last Hour Heat Produced ESP
  entity_id: sensor.m5atom_dev_total_produced_energy
  unique_id: statistics_sensor_atom_last_hour_heat_produced
  state_characteristic: change
  max_age:
    hours: 1
  keep_last_sample: false