- platform: statistics
  name: Kitchen Roof Humidity Stats
  entity_id: sensor.kitchen_roof_humidity
  state_characteristic: mean
  sampling_size: 20

- platform: derivative
  name: Kitchen Roof Humidity Change Rate
  source: sensor.kitchen_roof_absolute_humidity
  unit_time: h # Measures change in grams per hour
  time_window: 01:00:00 # Smooths out noise over 1 hour
