blueprint:
  name: Target Timeframes - Octopus Energy source
  description: Configures a target timeframe data source from Octopus Energy
  domain: automation
  author: BottlecapDave
  input:
    target_timeframe_data_source_sensor:
      name: Target timeframe data source sensor
      description: The data source sensor which represents the data source to update
      selector:
        entity:
          filter:
          - domain:
            - sensor
            integration: target_timeframes
          multiple: false
    octopus_energy_previous_day_rates:
      name: Previous day rates
      description: The previous day rates event sensor supplied by Octopus Energy.
        More information can be found at https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/entities/electricity/#previous-day-rates.
      selector:
        entity:
          filter:
          - domain:
            - event
            integration: octopus_energy
          multiple: false
    octopus_energy_current_day_rates:
      name: Current day rates
      description: The current day rates event sensor supplied by Octopus Energy.
        More information can be found at https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/entities/electricity/#current-day-rates.
      selector:
        entity:
          filter:
          - domain:
            - event
            integration: octopus_energy
          multiple: false
    octopus_energy_next_day_rates:
      name: Next day rates
      description: The next day rates event sensor supplied by Octopus Energy. More
        information can be found at https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/entities/electricity/#current-day-rates.
      selector:
        entity:
          filter:
          - domain:
            - event
            integration: octopus_energy
          multiple: false
  source_url: https://bottlecapdave.github.io/HomeAssistant-TargetTimeframes/blueprints/target_timeframes_octopus_energy.yaml
variables:
  target_timeframe_data_source_sensor: !input target_timeframe_data_source_sensor
  octopus_energy_previous_day_rates: !input octopus_energy_previous_day_rates
  octopus_energy_current_day_rates: !input octopus_energy_current_day_rates
  octopus_energy_next_day_rates: !input octopus_energy_next_day_rates
mode: queued
max: 4
triggers:
- platform: state
  entity_id: !input octopus_energy_previous_day_rates
- platform: state
  entity_id: !input octopus_energy_current_day_rates
- platform: state
  entity_id: !input octopus_energy_next_day_rates
condition: []
action:
- action: target_timeframes.update_target_timeframe_data_source
  data: "{%- set all_rates = [] -%} {%- if state_attr(octopus_energy_previous_day_rates,
    'rates') != None -%}\n  {%- set all_rates = all_rates + state_attr(octopus_energy_previous_day_rates,
    'rates') -%}\n{%- endif -%} {%- if state_attr(octopus_energy_current_day_rates,
    'rates') != None -%}\n  {%- set all_rates = all_rates + state_attr(octopus_energy_current_day_rates,
    'rates') -%}\n{%- endif -%} {%- if state_attr(octopus_energy_next_day_rates, 'rates')
    != None -%}\n  {%- set all_rates = all_rates + state_attr(octopus_energy_next_day_rates,
    'rates') -%}\n{%- endif -%} {%- set data = namespace(new_rates=[]) -%} {%- for
    rate in all_rates -%}\n  {%- set start = rate[\"start\"] | as_timestamp | timestamp_utc
    -%}\n  {%- set end = rate[\"end\"] | as_timestamp | timestamp_utc -%}\n  {%- set
    value = rate[\"value_inc_vat\"] | float -%}\n\n  {%- set metadata = { \"is_capped\":
    rate[\"is_capped\"] } -%}\n  {%- set new_rate = [{ 'start': start , 'end': end,
    'value': value, 'metadata': metadata }] -%}\n\n  {%- set data.new_rates = data.new_rates
    + new_rate -%}\n{%- endfor -%} {{ { 'data': data.new_rates } }}\n"
  target:
    entity_id: !input target_timeframe_data_source_sensor
